source 'https://rubygems.org'
ruby "2.3.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails',                    '4.2.1'
gem 'sass-rails',               '~> 5.0'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'will_paginate',            '3.0.7'
gem 'bootstrap-will_paginate',  '0.0.10'
gem 'uglifier',                 '>= 1.3.0'
gem 'coffee-rails',             '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',                 '~> 2.0'
gem 'sdoc',                     '~> 0.4.0', group: :doc
gem 'bcrypt',                   '~> 3.1.7'
gem 'carrierwave',              '0.10.0'
gem 'mini_magick',              '3.8.0'
gem 'fog',                      '1.36.0'
gem 'omniauth-facebook',        '3.0.0'
gem 'omniauth-instagram',       '~> 1.0', '>= 1.0.2'
gem 'omniauth-twitter',         '~> 1.2', '>= 1.2.1'
gem 'gibbon',			              '2.2.4'
gem 'sucker_punch',             '~> 2.0'
gem 'aws-sdk',                  '~> 2'
gem 'acts_as_votable',          '~> 0.10.0'
gem 'sitemap_generator'
gem 'httparty'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'figaro'
end

group :production do
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
  gem 'puma',           '3.1.0'
  gem 'newrelic_rpm'
end
